# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime
import yaml
import importlib

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('.'))

# -- Split configurations ----------------------------------------------------

from confs.schemas import _schemas
from confs.deploy import Deployment

_D = Deployment.current()
print('Deployment:', _D)

if _D.is_private():
    # For `.. only::` directive.
    tags.add('private') # type: ignore

with open('./confs/redirect.yml') as data:
    _redirects = yaml.safe_load(data)

# -- Project information -----------------------------------------------------

project = '银色子弹'
author = 'Shengyu Zhang'
copyright = '2020-%s, ' % datetime.now().year + author

# -- Non-standard project information ----------------------------------------

_logo = 'static/sphinxnotes.webp'
_description = 'Yes silver bullet here.'
_datefmt = '%Y-%m-%d'
_author_id = 'SilverRainZ'
_author_nick = 'LA'
_gh_owner = _author_id
_gh_repo = 'silverrainz.github.io'

# -- Enviroment information -----------------------------------------------------

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.email',
    'sphinx.ext.githubpages',
    'sphinxnotes.strike',
    'sphinxcontrib.plantuml',
    'sphinxcontrib.asciinema',
    'sphinx_copybutton',
    'sphinxcontrib.youtube',
    'sphinx_design',
    'sphinx_simplepdf', # .. pdf-include::
]

# Add any paths that contain templates here, relative to conf directory.
templates_path = ['templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_assets', '_images', 'README.rst']

# A string of reStructuredText that will be included at the end of every
# source file that is read.
rst_epilog = """
"""

# Provided by sphinxnotes.any
primary_domain = 'any'

# Use :code: as default role, so we can write `content` instead of ``content``.
default_role = 'code'

# Keep warnings as “system message” paragraphs in the built documents.
# Regardless of this setting, warnings are always written to the standard error
# stream when sphinx-build is run.
# See also suppress_
if _D.is_private():
    keep_warnings = True

# A list of warning codes to suppress arbitrary warning messages.
if _D is _D.Local:
    suppress_warnings = ['ref.' + x.objtype for x in _schemas]

# Auto numbered figures, tables and code-blocks if they have a caption.
# numfig = True

# Show codeauthor and sectionauthor directives produce any output in the built
# files.
show_authors = True

# A URL to cross-reference manpage directives.
manpages_url = 'https://man7.org/linux/man-pages/man{section}/{page}.{section}.html'

# Options for internationalisation -------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'
_language_full = '简体中文'

# -- Options for HTML output -------------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']

html_css_files = ['custom.css']

# A list of JavaScript filename.
# The entry must be a filename string or a tuple containing the filename string
# and the attributes dictionary. The filename must be relative to the
# html_static_path, or a full URI with scheme like https://example.org/script.js.
# The attributes is used for attributes of <script> tag. It defaults to an empty list.
html_js_files = []

html_baseurl = _D.url()

html_title = project

html_logo = _logo

html_favicon = 'static/favicon.webp'

# HTML theme configuration
html_theme = 'shibuya'
_htlm_theme_conf = importlib.import_module(f'confs.themes.{html_theme}')
html_theme_options = _htlm_theme_conf.html_theme_options
html_context = _htlm_theme_conf.html_context
html_sidebars = _htlm_theme_conf.html_sidebars
html_css_files.append(f'{html_theme}-custom.css')

# Setup announcement as your need
html_theme_options['announcement'] = '2025 年底翻新计划进行中，' \
'详见 <a href="https://github.com/SilverRainZ/silverrainz.github.io/issues/34">' \
'#34</a>'

if _D.is_mirror():
    if not _D.is_private():
        msg = f'''<p>
            这是部署于 {_D} 的镜像，访问源站点：
            <a class="source-page" href="{_D.Github.url()}">{_D.Github}</a>
        </p>'''
    else:
        msg = f'''<p>
            当前：{_D}，访问：
            <a class="source-page" href="{_D.Github.url()}">{_D.Github}</a> |
            <a class="source-page" href="{_D.Homelab.url()}">{_D.Homelab}</a> |
            <a class="source-page" href="{_D.Local.url()}">{_D.Local}</a>
        </p>'''
    html_theme_options['announcement'] = html_theme_options.get('announcement', '') + msg
    html_js_files.append('mirror-redirect.js')

# If true, the reST sources are included in the HTML build as _sources/name.
# I don't want to public my sources, so set it to false.
html_copy_source = True

html_search_language = language

html_last_updated_fmt = _datefmt

# A list of paths that contain extra files not directly related to the
# documentation.
html_extra_path = ['static/robots.txt', 'LICENSE']

# -- Options for LaTeX output -------------------------------------------------

latex_toplevel_sectioning = 'section'
latex_theme = 'howto'

# -- Per-extension configuration ---------------------------------------------------

extensions.append('sphinxnotes.mock')
mock_directives = []
mock_directives.append('contents') # Theme has built-in local-toc, see html_theme

extensions.append('sphinx.ext.todo')
todo_include_todos = True

extensions.append('sphinx.ext.extlinks')
extlinks = {
    'zhwiki': ('https://zh.wikipedia.org/wiki/%s', '📖 %s'),
    'enwiki': ('https://wikipedia.org/wiki/%s', '📖 %s'),
    'search': ('https://duckduckgo.com/?q=%s', '🔍 %s'),
    'twitter': ('https://twitter.com/%s', '👤 %s'),
    'ghuser': ('https://github.com/%s', '👤 %s'),
    'ghorg': ('https://github.com/%s', '👥 %s'),
    'ghrepo': ('https://github.com/%s', '⛺ %s'),
    'weibo': ('https://weibo.com/%s', '👤 %s'),
    'aur': ('https://aur.archlinux.org/packages/%s', '📦 %s'),
    'archpkg': ('https://archlinux.org/packages/%s', '📦 %s'),
    'archwiki': ('https://wiki.archlinux.org/index.php/%s', '📖 %s'),
    'zhihua': ('https://www.zhihu.com/answer/%s', '🙋 %s'),
    'zhihuq': ('https://www.zhihu.com/question/%s', '🤔 %s'),
    'zhihup': ('https://www.zhihu.com/people/%s', '👤 %s'),
    'pypi': ('https://pypi.org/project/%s', '📦 %s'),
    'lilydoc': ('https://lilypond.org/doc/Documentation/%s', None),
    'so.q': ('https://stackoverflow.com/a/%s', '🤔 %s'),
    'so.a': ('https://stackoverflow.com/a/%s', '🙋 %s'),
    'bili': ('https://www.bilibili.com/video/%s', '🎥 %s'),
    'musicca-drum': ('https://www.musicca.com/zh/drum-machine?data=%s', '🥁 %s'),
    'dudir': ('https://docutils.sourceforge.io/docs/ref/rst/directives.html#%s', '%s'),
    'durole': ('https://docutils.sourceforge.io/docs/ref/rst/roles.html#%s', '%s'),
}

extensions.append('sphinxnotes.any')
any_schemas = _schemas

extensions.append('ablog')
blog_path = 'blog'
blog_title = project
blog_baseurl = _D.url()
blog_authors = {
    _author_nick: (author, blog_baseurl),
}
blog_default_author = _author_nick
blog_languages = {
    language: (_language_full, None),
    # FIXME: https://github.com/sunpy/ablog/issues/136
    # 'en':     ('English',  None),
}
blog_default_language = language
post_date_format = _datefmt
post_auto_image = 1
blog_feed_fulltext = True
blog_feed_subtitle = _description
if _D.is_private():
    fontawesome_included = True
else:
    fontawesome_link_cdn = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
html_css_files.append('ablog-custom.css')

if _D.is_public():
    extensions.append('sphinxcontrib.gtagjs')
    gtagjs_ids = ['G-FYHS50G6DL']

if _D is _D.Local:
    extensions.append('sphinxnotes.snippet')
    snippetconfig = {}
    snippet_patterns = {
        'd': ['.*'],
        's': ['notes/.*', 'jour/.*', 'collections/.*', 'about/.*', 'p/.*', 'in/.*'],
        'c': ['p/.*', 'notes/man/.*'],
    }

if _D.is_public():
    extensions.append('sphinxnotes.isso')
    isso_url = 'https://comments.silverrainz.me:30500'
    isso_client_config = {
        'data-isso-vote': 'false', # disable voting as the css is broken
    }
    isso_include_patterns = ['**',]
    isso_exclude_patterns = ['index', 'in/**']

if _D.is_public():
    extensions.append('sphinx_sitemap')
    sitemap_filename = "sitemap.xml"
    sitemap_url_scheme = "{link}"

# NOTE: required by ablog
if not _D is _D.Local:
    extensions.append('sphinx.ext.intersphinx')
    # Although fetching intersphinx info is slow, but we have fasthtml now.
    intersphinx_mapping = {
        'python': ('https://docs.python.org/3', None),
        'sphinx': ('https://www.sphinx-doc.org/en/master', None),
        'srain': ('https://srain.silverrainz.me/', None),
    }

if _D.is_public():
    extensions.append('sphinx_reredirects')
    # https://documatt.gitlab.io/sphinx-reredirects/usage.html
    with open('./confs/redirect.yml') as data:
        redirects = _redirects

# extensions.append('sphinxcontrib.images')
# imagesconfig = {
#     'override_image_directive': True,
#     'cache_path': '_cache',
#     'download': True,
# }

extensions.append('sphinxnotes.lilypond')
lilypond_audio_volume = 300
lilypond_audio_format = 'mp3'
lilypond_include_paths = ['/p/ly/inc']

extensions.append('sphinxnotes.recentupdate')
recentupdate_date_format = _datefmt
recentupdate_exclude_path = []
recentupdate_exclude_commit = ['skip-recentupdate', 'conf']

if _D.is_public():
    extensions.append('sphinxext.opengraph')
    ogp_site_url = _D.url()
    ogp_site_name = project
    ogp_image = _D.url() + _logo

if _D is not _D.Local:
    # Doesn't work locally
    extensions.append('notfound.extension')
    notfound_urls_prefix = ''

extensions.append('sphinxnotes.comboroles')
comboroles_roles = {
    'parsed_literal': (['literal'], True),
    'sup_abbr': ['superscript', 'abbr',],

     # for ./blog/sphinxnotes-comboroles.rst
    'strong_literal': ['strong', 'literal'],
    'literal_enwiki': ['literal', 'enwiki'],
    'literal_strike': ['literal', 'strike'],
}

extensions.append('sphinxcontrib.globalsubs')
global_substitutions = {
    '?':        ':sup_abbr:`存疑 (笔者对此断言存有疑惑，请谨慎参考)`',
    'i':        ':sup_abbr:`个人观点 (这是笔者的个人观点，并无权威出处，请谨慎参考)`',
    'todo':     ':sup_abbr:`待补充 (但什么时候呢？)`',
    'how':      ':sup_abbr:`怎么做`',
    'why':      ':sup_abbr:`为什么`',
    'ref':      ':sup_abbr:`来源请求`',
    'n/a':      'ⁿ̷ₐ', # https://en.wikipedia.org/wiki/N/A

    # Marks for todo list.
    # Role octicon: https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html
    'o':    ':octicon:`issue-closed;1em;sd-text-success`', # done
    '.':    ':octicon:`issue-opened;1em;sd-text-warning`', # wip
    '_':    ':octicon:`issue-draft`',                      # todo
    'x':    ':octicon:`issue-closed;1em;sd-text-danger`',  # fail/wontdo/cancel

    # Marks for priority.
    'p0':   ':bdg-danger:`P0`',  # priv high
    'p1':   ':bdg-warning:`P1`', # priv medium
    'p2':   ':bdg-info:`P2`',    # priv low

    # Abbrs.
    'rst': 'reStructuredText',
}

if _D is not _D.Local:
    # Speed up local build (prevent read git timestamp).
    extensions.append('sphinx_last_updated_by_git')

if _D is _D.Local:
    # Speed up local incremental HTML build (may cause document inconsistencies).
    extensions.append('sphinxnotes.fasthtml')

extensions.append('sphinx.ext.graphviz')
graphviz_output_format = 'svg'

extensions.append('sphinxnotes.poc')

def setup(app):
    # Dump any domain data:
    # from conf.dump_any_domain import setup
    # setup(app)
    # Query artworks from LATree.

    from confs import fetch_artwork
    fetch_artwork.setup(app)

    ...
