#!/bin/bash

doc=$1
[ -f $doc ] || exit 1

root=$(git rev-parse --show-toplevel)
srcdir=$(mktemp -d)
builddir=$root/_build/singlepdf

mkdir -p $builddir
cp $root/$doc $srcdir/index.rst
sphinx-build -M latexpdf $srcdir $builddir --conf-dir $root

echo $builddir/latex/sphinx.pdf
