#!/bin/bash
# set -x

root=$(git rev-parse --show-toplevel)
cd $root

eval "$(snippet integration --sh)"
id=$(snippet_list --tags d)
file=$(snippet get $id --file)
docname=$(snippet get $id --docname)

new_file="$root/p/$(basename $file)"
new_docname="p/$(basename $docname)"

mv $file $new_file
if [[ "$docname" != "ronin"* ]]; then
    echo "$docname: /$new_docname.html" >> ./_conf/redirect.yml
    sed -i "1i:isso-id: /$docname\n" $new_file
    git add $file $new_file ./_conf/redirect.yml
else
    git add $new_file
fi

git diff HEAD
