# Definition of any domain's object schemas.
# See also https://sphinx.silverrainz.me/any/.

from sphinxnotes.any.api import Schema, Field as F, by_year, by_month, PathIndexer

by_hyphen = PathIndexer('-', 1)
by_hyphen2 = PathIndexer('-', 2)
by_slash = PathIndexer('/', 1)

_schemas = [
    Schema('friend',
           name=F(uniq=True, ref=True, required=True, form=F.Forms.LINES),
           attrs={'avatar': F(), 'blog': F()},
           content=F(form=F.Forms.LINES),
           description_template=open('_templates/friend.rst', 'r').read(),
           reference_template='👤{{ title }}',
           missing_reference_template='👤{{ title }}',
           ambiguous_reference_template='👥{{ title }}'),
    Schema('book',
           name=F(required=True, ref=True, form=F.Forms.LINES),
           attrs={
               'isbn': F(uniq=True, ref=True),
               'status': F(ref=True),
               'startat': F(ref=True, form=F.Forms.WORDS, indexers=[by_year]),
               'endat': F(ref=True, form=F.Forms.WORDS, indexers=[by_year]),
           },
           description_template=open('_templates/book.rst', 'r').read(),
           reference_template='《{{ title }}》',
           missing_reference_template='《{{ title }}》',
           ambiguous_reference_template='《{{ title }}》'),
    Schema('artwork',
           name=F(ref=True),
           attrs={
               'id': F(uniq=True, ref=True, required=True, indexers=[by_hyphen]),
               'date': F(ref=True, indexers=[by_year, by_month]),
               'medium': F(ref=True, form=F.Forms.WORDS),
               'size': F(ref=True),
               'image': F(),
               'album': F(ref=True),
           },
           description_template=open('_templates/artwork.rst', 'r').read(),
           reference_template='《{% if title %}{{ title }}{% else %}{{ id }}{% endif %}》',
           missing_reference_template='《{{ title }}》',
           ambiguous_reference_template='{{ title }}'),
    Schema('artist',
           name=F(uniq=True, ref=True, required=True, form=F.Forms.LINES),
           attrs={
               'movement': F(ref=True, form=F.Forms.WORDS),
               'gallery': F(ref=True, form=F.Forms.WORDS),
               'enwiki': F(),
               'zhwiki': F(),
               'artwork': F(form=F.Forms.WORDS),
           },
           description_template=open('_templates/artist.rst', 'r').read(),
           reference_template='🧑‍🎨{{ title }}',
           missing_reference_template='🧑‍🎨{{ title }}',
           ambiguous_reference_template='🧑‍🎨{{ title }}'),
    Schema('gallery',
           name=F(uniq=True, ref=True, required=True, form=F.Forms.LINES),
           attrs={'website': F()},
           description_template=open('_templates/gallery.rst', 'r').read(),
           reference_template='🖼️{{ title }}',
           missing_reference_template='🖼️{{ title }}'),
    Schema('event',
           name=F(ref=True, required=True),
           attrs={
               'date': F(ref=True, form=F.Forms.WORDS, indexers=[by_year]),
               'location': F(ref=True),
           },
           description_template=open('_templates/event.rst', 'r').read(),
           reference_template='📅{{ title }}',
           missing_reference_template='📅{{ title }}',
           ambiguous_reference_template='📅{{ title }}'),
    Schema('leetcode',
           name=F(ref=True, required=True),
           attrs={
               'id': F(uniq=True, ref=True),
               'diffculty': F(ref=True),
               'language': F(ref=True, form=F.Forms.WORDS),
               'key': F(ref=True, form=F.Forms.WORDS),
               'date': F(ref=True, form=F.Forms.WORDS, indexers=[by_year, by_month]),
               'reference': F(ref=True),
           },
           description_template=open('_templates/leetcode.rst', 'r').read(),
           reference_template='🧮{{ title }}',
           missing_reference_template='🧮{{ title }}',
           ambiguous_reference_template='🧮{{ title }}'),
    Schema('term',
           name=F(ref=True, required=True, form=F.Forms.LINES),
           attrs={
               'field': F(ref=True, indexers=[by_slash]),
               'enwiki': F(),
               'zhwiki': F(),
               'hide': F(),
           },
           description_template=open('_templates/term.rst', 'r').read(),
           reference_template='#️⃣{{ title }}',
           missing_reference_template='#️⃣{{ title }}',
           ambiguous_reference_template='#️⃣{{ title }}'),
    Schema('jour',
           name=F(ref=True, required=True),
           attrs={
               'date': F(ref=True, indexers=[by_year, by_month]),
               'category': F(),
           },
           description_template=open('_templates/jour.rst', 'r').read(),
           reference_template='📰{{ title }}',
           missing_reference_template='📰{{ title }}',
           ambiguous_reference_template='📰{{ title }}'),
    Schema('okr',
           name=F(ref=True, required=True),
           attrs={
               'id': F(uniq=True, ref=True, required=True, indexers=[by_hyphen2]),
               'krs': F(form=F.Forms.LINES),
               'hrs': F(form=F.Forms.WORDS),
               'progs': F(form=F.Forms.WORDS),
               'scores': F(form=F.Forms.WORDS),

               'p0': F(ref=True),
               'p1': F(ref=True),
               'p2': F(ref=True),
           },
           description_template=open('_templates/okr.rst', 'r').read(),
           reference_template='🎯{{ title }}',
           missing_reference_template='🎯{{ title }}',
           ambiguous_reference_template='🎯{{ title }}'),
Schema('people',
       name=F(uniq=True, ref=True, required=True, form=F.Forms.LINES),
       attrs={
           'github': F(),
           'blog': F(),
           'enwiki': F(),
           'zhwiki': F(),
           'weibo': F(),
       },
       description_template=open('_templates/people.rst', 'r').read(),
       reference_template='👤{{ title }}'),
Schema('rhythm',
       name=F(ref=True),
       attrs={
           'time': F(ref=True, required=True),
           'tempo': F(),
           'musicca': F(),
       },
       content=F(form=F.Forms.LINES),
       description_template=open('_templates/rhythm.rst', 'r').read(),
       reference_template='🥁{{ title }}'),
Schema('dev',
       name=F(ref=True, required=True),
       attrs={
           'id': F(uniq=True, ref=True, required=True, indexers=[by_hyphen]),
           'type': F(ref=True),
           'web': F(),
           'man': F(),
           'price': F(),
           'startat': F(ref=True, indexers=[by_year]),
           'endat': F(ref=True, indexers=[by_year]),
       },
       description_template=open('_templates/dev.rst', 'r').read(),
       reference_template='🎛️{{ title }}'),
Schema('loveletter',
       name=F(ref=True, required=True),
       attrs={
           'date': F(ref=True, required=True, indexers=[by_year]),
           'nick': F(),
           'author': F(ref=True),
           'createdat': F(indexers=[by_year]),
           'updatedat': F(indexers=[by_year]),
       },
       description_template=open('_templates/loveletter.rst', 'r').read(),
       reference_template='💌{{ title }}',
       missing_reference_template='💌{{ title }}',
       ambiguous_reference_template='💌{{ title }}'),
]

