html_theme_options = {
    'repository_url': f'https://github.com/SilverRainZ/bullet',
    'repository_branch': "master",
    'use_repository_button': True,
    'use_download_button': False,
    'use_edit_page_button': True,
    'use_source_button': True,
    'use_issues_button': False,
    'show_toc_level': 3,
    'navigation_with_keys': False, # https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#changing-pages-with-keyboard-presses
}

html_context = {}

_blog_post_page = [ # Provided by sphinx_book_theme
                  'navbar-logo',
                   # Provided by ABlog
                  'ablog/postcard', 'ablog/recentposts', 'ablog/tagcloud',
                  'ablog/categories', 'ablog/archives']

html_sidebars = {
    'blog': _blog_post_page, # ABlog's "All Posts" page
    'blog/**': _blog_post_page, # Inlucde posts and autogenerated pages
}


